import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import AddRouteForm from "../../../../components/Forms/AddRouteForm";

type Props = {};

function AddRoutePage({}: Props) {
  const router = useRouter();
  const { travelDayId } = router.query;

  if (!travelDayId) return <div>Nichts gefunden</div>;

  return (
    <div className="container m-auto">
      <Head>
        <title>Route erstellen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AddRouteForm id={+travelDayId} />
    </div>
  );
}

export default AddRoutePage;
