import Head from "next/head";
import React from "react";

type Props = {};

const Ausruestung = (props: Props) => {
  return (
    <div>
      <Head>
        <title>Ausrüstung</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Ausruestung</h1>;
    </div>
  );
};

export default Ausruestung;
