import Head from "next/head";
import React from "react";

type Props = {};

function Erstellen({}: Props) {
  return (
    <div>
      <Head>
        <title>Route erstellen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Route erstellen</h1>
    </div>
  );
}

export default Erstellen;
