import { useState } from "react";
import Head from "next/head";
import MapLibre from "../../components/MapLibre";
import Timeline from "../../components/timeline/Timeline";
import { GetServerSideProps } from "next";
import { PrismaClient } from "@prisma/client";
import { TravelDayWithRoute } from "../../@types/custom";

type Props = {
  travelDays: TravelDayWithRoute[];
  startDate: Date | undefined;
};

function RoutePage({ travelDays, startDate }: Props) {
  const [selectedRoute, setSelectedRoute] = useState<string | null>(null);
  const [hoveredRoute, setHoverRoute] = useState<string | null>(null);
  const [timeLineData, setTimeLineData] = useState([{}]);

  return (
    <div>
      <Head>
        <title>Route</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Content */}
      <div className="md:flex h-(screen-20)">
        <MapLibre
          route={travelDays}
          onClick={setSelectedRoute}
          selected={selectedRoute}
          hovered={hoveredRoute}
        />
        <div className="bg-white w-full h-80 overflow-y-auto md:h-full">
          <Timeline
            travelDays={travelDays}
            startDate={startDate}
            selected={selectedRoute}
            hovered={hoveredRoute}
            onClick={setSelectedRoute}
            onHover={setHoverRoute}
          />
        </div>
      </div>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const prisma = new PrismaClient();

  const data = await prisma.timeLine.findUnique({
    where: {
      userId_name: {
        userId: 1,
        name: "main",
      },
    },
    include: {
      timeLineHasTravelDays: {
        include: {
          travelDays: {
            include: {
              payments: true,
              route: true,
            },
          },
        },
      },
    },
  });

  const travelDays = data?.timeLineHasTravelDays.map(
    (travelDay) => travelDay.travelDays
  );

  const sortedTravelDay = travelDays?.sort((a, b) => {
    return new Date(a.date).getTime() - new Date(b.date).getTime();
  });
  const startDate = data?.startDate.toDateString();

  const travelDaysParsed = JSON.parse(JSON.stringify(sortedTravelDay));
  console.log("hier");
  console.log(travelDaysParsed);
  console.log("vorbei");

  // Pass data to the page via props
  return { props: { travelDays: travelDaysParsed, startDate } };
};

export default RoutePage;
