import Head from "next/head";
import Link from "next/link";

function Route() {
  return (
    <div>
      <Head>
        <title>Route</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Route</h1>
      <Link href={"/route/erstellen"}>Neue Strecke Erstellen</Link>
    </div>
  );
}

export default Route;
