import Head from "next/head";
import styles from "../styles/Home.module.css";

function UeberUns() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nikas Journey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Über uns</h1>
      </main>

      <footer className={styles.footer}>Footer</footer>
    </div>
  );
}

export default UeberUns;
