import Head from "next/head";
import React from "react";
import Form from "../../components/Form";

type Props = {};

function Erstellen({}: Props) {
  return (
    <div className="container m-auto">
      <Head>
        <title>Route erstellen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form />
    </div>
  );
}

export default Erstellen;
